### PR TITLE
Add an .npmignore file

### LINKED ISSUE #71: Add .npmignore

### PR DESCRIPTION
**Pull request by jpangelle**
Aims to make the published package leaner by ignoring developer specific files.

By default, `npm` ignores the files in the `.gitignore`. However, if a `.npmignore` file is added, then only that file will be evaluated by `npm`. Therefore, I added the files that were in our `.gitignore` into the `.npmignore` as well.

[Source](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)

---

Notable files that I did **not** add to the `.npmignore`:
- Non-test `src` files
- `LICENSE`
- `package.json`
- `README.md`
- `yarn.lock`

Closes #71

### CODE REVIEW

**Comment by zakangelle** [comment]
Do we want `bin` ignored? That's what consumers use.

**Comment by jpangelle** [comment]
> Do we want `bin` ignored? That's what consumers use.

Well since `bin` was in the `.gitignore`, I figured it was already being ignored anyway.

**Comment by zakangelle** [comment]
It's ignored from being tracked by git, because it contains our compiled artifact and type declarations, but we don't want it to be npm-ignored, otherwise it won't be published.

**Comment by jpangelle** [comment]
> It's ignored from being tracked by git, because it contains our compiled artifact and type declarations, but we don't want it to be npm-ignored, otherwise it won't be published.

Well then I am confused how it was ever being part of the `npm` package since `npm` by default ignores the files in the `.gitignore`.

**Comment by zakangelle** [comment]
No idea - I've never used `.npmignore` files. It's definitely publishing `bin` right now - you can see it when you `npm install` our library.

**Comment by zakangelle** [comment]
Maybe has something to do with `bin` being generated by our `prepare` script? Might be worth looking into.

**Pull request merged**
