### PR TITLE
fix: move dependencies to devDependencies and peerDependencies

### PR DESCRIPTION
**Pull request by padupuy**
According to the documentation https://nodejs.org/uk/blog/npm/peer-dependencies/ and stackOverflow https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins, in this package there is no need to add axios as dependency but only peerdependency.

### CODE REVIEW

**Comment by zakangelle** [comment]
Yeah, I'm kind of on the fence about making it a peer dependency right now. For most common use cases, consumers will not need to use `axios` directly. However in cases where consumers need to pass in an `axiosInstance` or do things like set headers globally, they would in fact use it directly.

For now, we'll keep it as a direct dependency, but this is a decision we will revisit as the library matures.

**Comment by padupuy** [comment]
@zakangelle maybe we could add to the documentation to install axios as a dependency too

with npm:
```
npm install --save axios use-axios-client
```
with yarn:
```
$ yarn add axios use-axios-client
```

I think it will prevent a mismatch bug if an application already use a version and this library depends on another one

**Comment by zakangelle** [comment]
@padupuy That's a good point. The more I think about it, the more I think having it as a peer dependency makes sense, as you originally suggested. Going to re-open this and look at it locally tomorrow.

**Comment by zakangelle** [comment]
Merging this - feels like a breaking change since any consumers currently using the library who don't have `axios` as a direct dependency will now be required to install it.

Will plan to do a 2.0 release sometime next week after we patch a few more things. Thanks for the help.

**Pull request merged**
